#!/usr/bin/env bash

DIRNAME="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
BABEL_BIN="$DIRNAME/../node_modules/.bin/babel"
PACKAGES_DIR="$DIRNAME/../packages"

cd $PACKAGES_DIR

for dir in */; do
  cd $dir
  $BABEL_BIN ./src -d ./dist --copy-files --ignore=**/*.test.js &
  cd $PACKAGES_DIR
done
